### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

### ISSUE THREAD

**Issue by SkullFang** [yym6472/ConSERT#30]
torch 1.6.0 and torch 1.8.1 not work. assert this error like title.

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from sentence_transformers import models, losses
  File "/root/ConSERT/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, SentenceLabelDataset, ParallelSentencesDataset
  File "/root/ConSERT/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .sampler import *
  File "/root/ConSERT/sentence_transformers/datasets/sampler/__init__.py", line 1, in <module>
    from .LabelSampler import *
  File "/root/ConSERT/sentence_transformers/datasets/sampler/LabelSampler.py", line 6, in <module>
    from ...datasets import SentenceLabelDataset
  File "/root/ConSERT/sentence_transformers/datasets/SentenceLabelDataset.py", line 8, in <module>
    from .. import SentenceTransformer
  File "/root/ConSERT/sentence_transformers/SentenceTransformer.py", line 11, in <module>
    import transformers
  File "/root/ConSERT/transformers/__init__.py", line 22, in <module>
    from .integrations import (  # isort:skip
  File "/root/ConSERT/transformers/integrations.py", line 58, in <module>
    from .file_utils import is_torch_tpu_available
  File "/root/ConSERT/transformers/file_utils.py", line 140, in <module>
    from apex import amp  # noqa: F401
  File "/root/miniconda3/lib/python3.8/site-packages/apex/__init__.py", line 27, in <module>
    from . import transformer
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/__init__.py", line 4, in <module>
    from apex.transformer import pipeline_parallel
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 3, in <module>
    from apex.transformer.pipeline_parallel.schedules.fwd_bwd_no_pipelining import (
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in <module>
    from apex.transformer.pipeline_parallel.schedules.common import Batch
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/pipeline_parallel/schedules/common.py", line 9, in <module>
    from apex.transformer.pipeline_parallel.p2p_communication import FutureTensor
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/pipeline_parallel/p2p_communication.py", line 25, in <module>
    from apex.transformer.utils import split_tensor_into_1d_equal_chunks
  File "/root/miniconda3/lib/python3.8/site-packages/apex/transformer/utils.py", line 11, in <module>
    torch.distributed.all_gather_into_tensor = torch.distributed._all_gather_base
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

this error in apex
https://github.com/NVIDIA/apex/issues/1526

apex not match torch version, can you tell me your torch version?

**Comment by zhou-wb** [comment]
try to use an old version of apex:
``` bash
git clone https://github.com/NVIDIA/apex
cd apex
git checkout 22.05-dev
pip install -v --disable-pip-version-check --no-cache-dir ./
```
